sudo: false

language: node_js

node_js:
  - '10'
  - '12'
  - '14'
  - '15'

branches:
  only:
    - nyc
    - master
    - travis-ci

install:
  - ls
  - for dir in proof.*; do (cd $dir && npm install --no-package-lock --no-save); done
  - npm install -g nyc prove

script:
  - nyc --exclude test.js --exclude '*/test/**' node test
