sudo: false

language: node_js

node_js:
  - '10'
  - '12'
  - '14'
  - '15'

branches:
  only:
    - nyc
    - master
    - travis-ci

install:
  - ls
  - for dir in proof.*; do (cd $dir && [[ -e package.json && ! -e skip ]] && npm install --no-save --no-package-lock || true); done && git checkout .
  - npm install -g nyc prove@8.0.3

script:
  - nyc --exclude test.js --exclude '*/test/**' node test
