sudo: false

language: node_js

node_js:
  - '12'
  - '10'

branches:
  only:
    - nyc
    - master
    - travis-ci

install:
  - npm install --no-package-lock --no-save
  - npm install -g nyc

script:
  - echo custom script
  - nyc npm test
