sudo: false

language: node_js

node_js:
  - '12'
  - '10'

branches:
  only:
    - nyc
    - master
    - travis-ci

install:
  - cd proof.runner && npm install --no-package-lock --no-save
  - npm install -g nyc

script:
  - cd proof.runner && nyc npm test
