#!/bin/sh

set -e

echo ""

(node proof.bin.js run t/*/*.t.js | tee .proof.out | node proof.bin.js progress) \
    || (node proof.bin.js errors < .proof.out) \
    || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  istanbul report --format text
  echo ""

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | coveralls)
fi

echo ""
