name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: for dir in proof.*; do (cd $dir && npm install --no-package-lock); done
    - name: npm ls
      run: npm ls
    - name: npm install nyc, prove, codecov
      run:  npm install -g nyc prove codecov
    - name: where is stuff?
      run: |
        which nyc
        which codecov
        which proof
    - name: npm test
      run: nyc --exclude test.js --exclude '*/test/**' node test
      env:
        CI: true
    - name: generate codecov report
      run: nyc report --reporter=text-lcov > coverage.lcov
    - name: ship coverage to codecov
      run: codecov --branch=${GITHUB_REF##*/}
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
